repos:

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.0
    hooks:
    -   id: ruff-check
        name: ruff check
        description: "Run 'ruff check' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        args: [--fix, --show-fixes]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

    -   id: ruff-format
        name: ruff format
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

    # Legacy alias
    -   id: ruff
        name: ruff (legacy alias)
        description: "Run 'ruff check' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        args: [--fix]
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
