[project]
name = "changelogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "frontmatter>=3.0.8",
    "pydantic>=2.11.9",
    "python-frontmatter>=1.1.0",
    "rich>=14.1.0",
    "typer>=0.17.4",
]

[project.scripts]
changelogger = "main:app"

# And the pytest config to find your code in 'src'
[tool.pytest.ini_options]
pythonpath = "src"
testpaths = [
    "tests",
]

[tool.changelogger]
changelog_file = "CHANGELOG.md"
fragments_dir = ".changelog/"

# Sections are mapped from the Enum members here
[tool.changelogger.sections]
"feature" = { title = "🚀 New Features" }
"fix" = { title = "🐛 Bug Fixes" }
"docs" = { title = "📚 Documentation" }
"internal" = { title = "🔧 Internal Changes" }

# New optional section for linking tickets
[tool.changelogger.tickets]
base_url = "https://your-jira-instance.com/browse/"

[tool.black]
line-length = 88
skip-string-normalization = true


[tool.ruff]
line-length = 88

src = ["src"]

[tool.ruff.lint]
select = ["ALL"]

ignore = [
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    "D203", "D212", "COM812", "EM101", "ISC001", "TRY003", "DTZ011",
    "E203", "E501", "ERA001"
]
[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["S101"]

[tool.ruff.format]
quote-style = "double"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pytest-cov>=7.0.0",
]
